#!/system/bin/sh
cd $1
busybox mkdir home >> /dev/zero
busybox clear
for tar in /sdcard/*.tar.gz
do
busybox tar -C $OI/.. -xvf $tar
rm $tar
done
busybox clear
#Write your init code here!
busybox echo "Android OIDE 2.3.2"
busybox echo "Make by SpringHack"


