#!/system/bin/sh
cd $1
busybox mkdir home >> /dev/zero
busybox clear
busybox chmod 777 $OI/../init
$OI/../init
busybox clear
#Write your initial code in file 'init'!
busybox echo "Android OIDE 2.6.0"
busybox echo "Make by SpringHack"


